### ISSUE TITLE
Add Bitcoin's RPC user and password to compose file for middleware service

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel#11]
`configure-box.sh` should add RPC_USER and RPC_PASSWORD to the middleware service in `docker-compose.yml`. 

```
middleware:
                image: getumbrel/middleware:v0.0.5
                depends_on: [ bitcoin, lnd ]
                logging: *default-logging
                restart: on-failure
                network_mode: host
                volumes:
                    - "${HOME}/lnd:/lnd"
                environment:
                    BITCOIN_HOST: "0.0.0.0"
                    RPC_PORT: "8332"
                    RPC_USER: "<bitcoind rpc username here>"
                    RPC_PASSWORD: "<bitcoind rpc password here>"
                    LND_NETWORK: "mainnet"
                    LND_HOST: "127.0.0.1"
```
