### ISSUE TITLE
installed a bazarr docker alongside and connected to umbrel's docker network but no files

### ISSUE THREAD

**Issue by teasider** [getumbrel/umbrel#1568]
Hi everyone, not much experience with dockers.

I've docker composed a bazarr docker to work along side sonarr and radarr while connecting to the umbrel network bridge (to be included in the same subnet as all umbrel's apps)

everything works, even the connections to radarr and sonarr - but i cant see any files.
do i need to set up anything else in the docker-compose file to be able to access the files on the host? (where the movies and shows are?)

I am able to see the movies and tv shows on bazarr - but I guess thats only becuase ive linked their APIs.
I get this error in bazarr:

`FileNotFoundError: [Errno 2] No such file or directory: \'/downloads/shows/Slow Horses/Season 2/filename.mkv\
`

I guess that's becuase the bazarr docker dont have real access to the host's files? 
When trying to use 'add path' the only directories i can see are:
/app/
/bin/
/command/
/config/

would love some feedback on the subject, thank you

the docker-compse i used:

```
---
version: "2.1"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - /home/e/bazarr/config:/config
      - /umbrel/data/storage/downloads/movies:/movies #optional
      - /umbrel/data/storage/downloads/shows:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - umbrel_main_network
networks:
  umbrel_main_network:
    external: true
```
