### ISSUE TITLE
Allow applications to bypass umbrel authentication

### ISSUE THREAD

**Issue by MontejoJorge** [getumbrel/umbrel#1716]
There are few apps that I think there is no need (or even is annoying) to login in umbrel before the app, and then login in the app.
Maybe add some configuration to add a list of installed apps that could bypass the umbrel auth.

**Comment by toome123** [comment]
There it is such configuration. It’s called `PROXY_AUTH_ADD`
Checkout deps/app-proxy directly for more configuration details

**Comment by MontejoJorge** [comment]
Thats nice @toome123 but for the common user it would be better to add the option in the GUI

**Comment by highghlow** [comment]
> it would be better to add the option in the GUI

+1

**Comment by kerbless** [comment]
+1

**Comment by MontejoJorge** [comment]
Hey @lukechilds I would like to work on this issue!

**Comment by decentropy** [comment]
maybe I don't understand docs... but creating  a .env file in the app-data folder with PROXY_AUTH_ADD=false did not work for me.

it still forces redirect to umbrel login (port 2000), making my nginx reverse proxy unusable.
Quite frankly a deal breaker... I need simple way to expose service when I want to... so I'm trying CasaOS.

If I'm misunderstanding, would be happy to try again - but the docs linked above aren't very clear on what to do, to disable auth per app.

**Comment by jayma777** [comment]
For anyone that still needs it:
Ensure the docker-compose.yml is formatted correctly.  (Two spaces per "indent", no tabs)
My docker-compose.yml:   (Adapt as needed)
```
version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: searxng_web_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: false
    container_name: searxng_app_proxy_1
  web:
    image: >-
      ghcr.io/searxng/searxng:2025.12.9-b719d559b@sha256:95e59f5ba7d48b4c7ee92f2705907e52c5b98715b0d8c4802863322a502a8c4a
    restart: on-failure
    environment:
      SEARXNG_SECRET: ${APP_SEED}
    volumes:
      - ${APP_DATA_DIR}/data/config:/etc/searxng
      - ${APP_DATA_DIR}/data/cache:/var/cache/searxng
    container_name: searxng_web_1
```

Save to /home/umbrel/umbrel/app-data/searxng/docker-compose.yml

Restart the app in the umbrel dashboard.  Happy searching!

I agree that this should be a GUI selection.
