### ISSUE TITLE
How to configure to use gluetun with qbittorrent or transmission?

### ISSUE THREAD

**Issue by piyush97** [getumbrel/umbrel#1743]
I'm binding my VPN using gluetun to my qbittorrent/transmission containers. 
I am using `network_mode: 'container:gluetun'` and when I curl, i am connected to my vpn's ip. I am unable to use the default ui for qbittorrent. 

My docker-compose:

```yaml
version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: qbittorrent_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"
    network_mode: "container:gluetun"

  server:
    image: hotio/qbittorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORTS=8080/tcp,8080/udp
      - UMASK=002
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - /media/media-for-home:/downloads
    restart: on-failure
    network_mode: "container:gluetun"
  
```

My gluetun:
```yaml
version: "2"
services:
  gluetun:
    image: qmcgaw/gluetun:v3@sha256:e15ede3ce007e3f6e3f6532c7d8d6051f4bb0dca4bb3c5edd7aa3316916e9990
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8111:8000/tcp # Built-in HTTP control server
      - 6081:6881
      - 6081:6881/udp
      - 6011:6011
    # command:
    volumes:
      - /media/media-for-home/gluetun:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      # More variables are available, see the Wiki table
      - VPNSP=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER="my-user-id"
    restart: always

**Comment by basziee** [comment]
this is my compose for gluetun:
```yml
version: '3.8'
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /appdata/gluetun:/gluetun
    environment:
      VPN_SERVICE_PROVIDER: redacted
      OPENVPN_USER: redacted
      OPENVPN_PASSWORD: redacted
      DNS_ADDRESS: 1.1.1.1
      OVPN_DISABLE_PUSH_BLOCK_DNS: 0
      TZ: Europe/London
      HTTPPROXY: off
      SHADOWSOCKS: off
    networks:
      - gluetun_bridge
    restart: unless-stopped
    
networks:
  gluetun_bridge:
    name: gluetun_bridge
```

and this is an sample app

```yml
services:
  hello:
    image: alpine
    command: sh -c "echo 'Hello, world!' && wget http://ipecho.net/plain -O - -q ; echo"
    network_mode: "container:gluetun"
```
