### ISSUE TITLE
How to append usb storage to umbrel?

### ISSUE THREAD

**Issue by wesleyguirra** [getumbrel/umbrel#1835]
How to append usb storage to umbrel? so it can be used for app data and other stuff like movies.

I've modified my docker-compose to include volume `mnt/kodak` and also added some changes to volumes config, but it didn't worked as expected.

Here's my `docker-compose.yml` for reference

```yaml
version: '3.7'

services:
        tor_proxy:
                container_name: tor_proxy
                image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
                user: "1000:1000"
                restart: on-failure
                volumes:
                    - ${PWD}/tor/torrc-proxy:/etc/tor/torrc:ro
                    - ${PWD}/tor/data:/data
                environment:
                    HOME: "/tmp"
                ports:
                  - "127.0.0.1:$TOR_PROXY_PORT:$TOR_PROXY_PORT"
                networks:
                    default:
                        ipv4_address: $TOR_PROXY_IP
        nginx:
                container_name: nginx
                image: nginx:1.17.8@sha256:380eb808e2a3b0dd954f92c1cae2f845e6558a15037efefcabc5b4e03d666d03
                depends_on: [ dashboard, manager ]
                volumes:
                        - ${PWD}/nginx:/etc/nginx
                restart: on-failure
                stop_grace_period: 30s
                ports:
                    - "${NGINX_PORT}:80"
                networks:
                    default:
                        ipv4_address: $NGINX_IP
        dashboard:
                container_name: dashboard
                image: getumbrel/dashboard:0.5.4@sha256:0662567cc1b0ba2179f65bfae0472d085a7e79f53f502e8d1789a1ecba58744b
                restart: on-failure
                stop_grace_period: 1m30s
                networks:
                    default:
                        ipv4_address: $DASHBOARD_IP
        manager:
                container_name: manager
                image: getumbrel/manager:0.5.4@sha256:400559b951ec19b9e79c5eec96bf2a11efd57a7f9c65f9a8cc03e6ff833e9a59
                restart: on-failure
                stop_grace_period: 5m30s
                volumes:
                        - ${PWD}:${PWD}
                        - ${PWD}/info.json:/info.json
                        - ${PWD}/db:/db
                        - ${PWD}/jwt:/jwt
                        - ${PWD}/events/signals:/signals
                        - ${PWD}/app-data:/app-data
                        - ${PWD}/repos:/repos
                        - ${PWD}/statuses:/statuses
                        - ${PWD}/tor/data:/var/lib/tor/
                        - /var/run/docker.sock:/var/run/docker.sock
                        - ${DOCKER_BINARY:-/usr/bin/docker}:/usr/bin/docker
                        - /mnt/kodak:/mnt/kodak
                environment:
                    PORT: "3006"
                    USER_PASSWORD_FILE: "/db/user.json"
                    JWT_PUBLIC_KEY_FILE: "/jwt/jwt.pem"
                    JWT_PRIVATE_KEY_FILE: "/jwt/jwt.key"
                    JWT_EXPIRATION: "604800"
                    DOCKER_COMPOSE_DIRECTORY: $PWD
                    UMBREL_SEED_FILE: "/db/umbrel-seed/seed"
                    UMBREL_DASHBOARD_HIDDEN_SERVICE_FILE: "/var/lib/tor/web/hostname"
                    UMBREL_AUTH_SECRET: $UMBREL_AUTH_SECRET
                    BITCOIN_P2P_HIDDEN_SERVICE_FILE: "/var/lib/tor/bitcoin-p2p/hostname"
                    BITCOIN_P2P_PORT: $BITCOIN_P2P_PORT
                    BITCOIN_RPC_HIDDEN_SERVICE_FILE: "/var/lib/tor/bitcoin-rpc/hostname"
                    BITCOIN_RPC_PORT: $BITCOIN_RPC_PORT
                    BITCOIN_RPC_USER: $BITCOIN_RPC_USER
                    BITCOIN_RPC_PASSWORD: $BITCOIN_RPC_PASS
                    LND_REST_HIDDEN_SERVICE_FILE: "/var/lib/tor/lnd-rest/hostname"
                    LND_GRPC_HIDDEN_SERVICE_FILE: "/var/lib/tor/lnd-grpc/hostname"
                    LND_CERT_FILE: "/lnd/tls.cert"
                    LND_ADMIN_MACAROON_FILE: "/lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/admin.macaroon"
                    SHUTDOWN_SIGNAL_FILE: "/signals/shutdown"
                    REBOOT_SIGNAL_FILE: "/signals/reboot"
                    GITHUB_REPO: "getumbrel/umbrel"
                    UMBREL_VERSION_FILE: "/info.json"
                    UPDATE_STATUS_FILE: "/statuses/update-status.json"
                    UPDATE_SIGNAL_FILE: "/signals/update"
                    UPDATE_LOCK_FILE: "/statuses/update-in-progress"
                    BACKUP_STATUS_FILE: "/statuses/backup-status.json"
                    DEBUG_STATUS_FILE: "/statuses/debug-status.json"
                    REPO_UPDATE_STATUS_FILE: "/statuses/repo-update-status.json"
                    TOR_HIDDEN_SERVICE_DIR: "/var/lib/tor"
                    IS_UMBREL_OS: ${IS_UMBREL_OS:-"false"}
                    UMBREL_APP_REPO_URL: "https://github.com/getumbrel/umbrel-apps.git"
                networks:
                    default:
                        ipv4_address: $MANAGER_IP
        auth:
                container_name: auth
                image: getumbrel/auth-server:v0.5.1@sha256:afcd9065eab02f98ee6bf705045170a4b385fb5f81e3b168bb92ffb8ac7a1760
                user: "1000:1000"
                #build: ./deps/app-auth
                restart: on-failure
                environment:
                    PORT: $AUTH_PORT
                    UMBREL_AUTH_SECRET: $UMBREL_AUTH_SECRET
                    MANAGER_IP: $MANAGER_IP
                    MANAGER_PORT: 3006
                    DASHBOARD_IP: $DASHBOARD_IP
                    DASHBOARD_PORT: 3004
                volumes:
                        - ${PWD}/tor/data:/var/lib/tor:ro
                        - ${PWD}/app-data:/app-data:ro
                ports:
                    - "${AUTH_PORT}:${AUTH_PORT}"
                networks:
                    default:
                        ipv4_address: $AUTH_IP
networks:
    default:
      name: umbrel_main_network
      ipam:
          driver: default
          config:
              - subnet: "$NETWORK_IP/16"a
volumes:
  app-data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/kodak
      o: bind
```
