### ISSUE TITLE
Improved Duplicati application to enable encryption. 

### ISSUE THREAD

**Issue by Emilien-Lambert** [getumbrel/umbrel#1906]
It would be really great to add the parameter `‘--encryption-module=aes’` to the list of entrypoints in the `docker-compose.yaml` of the Duplicati application. 

This will enable encryption of backups, which isn't currently present. 

Like : 

```yaml
version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: duplicati_duplicati_1
      APP_PORT: 8200
      PROXY_AUTH_ADD: 'false'
    container_name: duplicati_app_proxy_1
  duplicati:
    image: >-
      duplicati/duplicati:2.0.8.1_beta_2024-05-07@sha256:97b8ef7bcaa095793ef9f39049851f987860a8c832aaf67ef977ff398f9e996e
    entrypoint:
      - /usr/bin/duplicati-server
      - '--webservice-port=8200'
      - '--webservice-interface=any'
      - '--webservice-password=${APP_PASSWORD}'
      - '--webservice-allowed-hostnames=*'
      - '--encryption-module=aes'
    user: '1000:1000'
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${UMBREL_ROOT}/data/storage:/umbrel
    container_name: duplicati_duplicati_1
```
