### ISSUE TITLE
1.2.2 to 1.3 update failed: Mender not installed

### ISSUE THREAD

**Issue by bocekm** [getumbrel/umbrel#1955]
I'm running Umbrel 1.2.2 in a docker container on Synology NAS installed per https://mariushosting.com/how-to-install-umbrel-os-on-your-synology-nas/ (thanks, @mariushosting).

When I try to update to 1.3 through the web UI, I get `Error: Mender not installed`.
![Screenshot from 2024-12-11 22-21-01](https://github.com/user-attachments/assets/7be583c9-4c3c-4284-be86-8d3d33674b44)

What's the best way to go about it?
Is there anything missing in the Docker compose file mentioned in the article?
```
services:
  umbrel:
    image: dockurr/umbrel
    container_name: Umbrel-OS
    healthcheck:
       test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/80' || exit 1
       interval: 10s
       timeout: 5s
       retries: 3
       start_period: 90s
    ports:
      - 3253:80
    volumes:
      - /volume1/docker/umbrel:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure:5
```
