### ISSUE TITLE
Env variable problem

### ISSUE THREAD

**Issue by techtastet** [getumbrel/umbrel#878]
Hi, same problem here
```
ERROR: The Compose file './../docker-compose.yml' is invalid because:
networks.default.ipam.config.subnet is invalid: should use the CIDR format
services.tor.ports contains an invalid type, it should be a number, or an object
services.bitcoin.ports contains an invalid type, it should be a number, or an object
services.electrs.ports contains an invalid type, it should be a number, or an object
services.lnd.ports contains an invalid type, it should be a number, or an object
services.lnd.ports contains an invalid type, it should be a number, or an object
services.nginx.ports contains an invalid type, it should be a number, or an object
services.lnd.ports value ['9735:9735', ':', ':'] has non-unique elements
```

And in the `docker-compose.yml`file, the example for the lnd service:
```yaml
        lnd:
                container_name: lnd
                image: lncm/lnd:v0.12.1@sha256:bdc442c00bc4dd4d5bfa42efd7d977bf$
                depends_on: [ tor, manager ]
                volumes:
                        - ${PWD}/lnd:/data/.lnd
                restart: on-failure
                stop_grace_period: 5m30s
                ports:
                    - "9735:9735"
                    - "$LND_REST_PORT:$LND_REST_PORT"
                    - "$LND_GRPC_PORT:$LND_GRPC_PORT"
                networks:
                    default:
                        ipv4_address: $LND_IP
```

Environments variables seem to be deleted from the system, can I do something to restore them, or do I need to reinstall my node ?
